spring:
  cloud:
    config:
      uri: http://localhost:8001
  config:
    import: configserver:http://localhost:8001
  application:
    name: ClientService

server:
  port: 8084

my.service : ClientService from GIT REPO
